import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  keyboardView: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleSection: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    gap: 8,
  },
  headerStatusBadge: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  headerStatusText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.white,
  },
  decisionTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  stepIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: COLORS.white,
  },
  stepDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.background,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    borderWidth: 2,
    borderColor: COLORS.border,
  },
  stepDotActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  stepDotCurrent: {
    borderColor: COLORS.accent,
    borderWidth: 3,
  },
  stepDotText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  stepDotTextActive: {
    color: COLORS.white,
  },
  savingIndicator: {
    marginLeft: 8,
  },
  shareStepBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(142,36,170,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 6,
  },
  scrollContent: {
    padding: 16,
  },
  stepContent: {
    flex: 1,
  },
  stepTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: 8,
  },
  stepDescription: {
    fontSize: 14,
    color: COLORS.textSecondary,
    lineHeight: 20,
    marginBottom: 20,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.primary,
    marginBottom: 8,
    marginTop: 8,
  },
  factorCard: {
    marginBottom: 8,
    padding: 12,
  },
  factorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  factorName: {
    fontSize: 15,
    fontWeight: '500',
    color: COLORS.textPrimary,
    flex: 1,
  },
  categoryButtons: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  categoryButton: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
  },
  categoryButtonActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  categoryText: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  categoryTextActive: {
    color: COLORS.white,
  },
  addFactorRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
    marginBottom: 16,
  },
  addInput: {
    flex: 1,
    height: 48,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 15,
    color: COLORS.textPrimary,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  addButton: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Reorder styles for Step 4
  reorderCard: {
    marginBottom: 8,
    padding: 12,
  },
  reorderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reorderRank: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  rankNumber: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.white,
  },
  reorderName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '500',
    color: COLORS.textPrimary,
  },
  reorderButtons: {
    flexDirection: 'row',
    gap: 4,
  },
  arrowButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: COLORS.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  arrowButtonDisabled: {
    opacity: 0.5,
  },
  tipBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: 'rgba(142, 36, 170, 0.08)',
    borderRadius: 12,
    padding: 12,
    marginTop: 16,
    gap: 8,
  },
  tipText: {
    flex: 1,
    fontSize: 13,
    color: COLORS.textSecondary,
    lineHeight: 18,
  },
  // Rating display styles for Step 5
  ratingCard: {
    marginBottom: 8,
    padding: 12,
  },
  ratingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  ratingRank: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  ratingBadge: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  ratingBadgeText: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.white,
  },
  ratingBarContainer: {
    height: 6,
    backgroundColor: COLORS.divider,
    borderRadius: 3,
    overflow: 'hidden',
  },
  ratingBarFill: {
    height: '100%',
    backgroundColor: COLORS.primary,
    borderRadius: 3,
  },
  // Gap selector styles (Step 5)
  gapSelectorCard: {
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  gapHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  gapSelectorTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  gapCurrentBadge: {
    backgroundColor: 'rgba(142,36,170,0.1)',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
  },
  gapCurrentBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.primary,
  },
  gapChipsScroll: {
    marginTop: 6,
  },
  gapChipsRow: {
    flexDirection: 'row',
    gap: 6,
    paddingRight: 8,
  },
  gapChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  gapChipActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  gapChipWarn: {
    borderColor: '#FCD34D',
    backgroundColor: 'rgba(245,158,11,0.05)',
  },
  gapChipWarnActive: {
    backgroundColor: '#F59E0B',
    borderColor: '#F59E0B',
  },
  gapChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  gapChipTextActive: {
    color: COLORS.white,
  },
  gapChipTextWarn: {
    color: '#D97706',
  },
  gapChipTextWarnActive: {
    color: COLORS.white,
  },
  gapWarningBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    padding: 10,
    backgroundColor: 'rgba(245,158,11,0.08)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FCD34D',
  },
  gapWarningText: {
    flex: 1,
    fontSize: 12,
    color: '#92400E',
    lineHeight: 17,
  },
  perFactorGapRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 6,
  },
  perFactorGapLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: COLORS.textMuted,
    minWidth: 80,
  },
  gapChipSmall: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  gapChipSmallActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  gapChipSmallWarn: {
    borderColor: '#FCD34D',
    backgroundColor: 'rgba(245,158,11,0.05)',
  },
  gapChipSmallWarnActive: {
    backgroundColor: '#F59E0B',
    borderColor: '#F59E0B',
  },
  gapChipSmallText: {
    fontSize: 10,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  gapChipSmallTextActive: {
    color: COLORS.white,
  },
  gapChipSmallTextWarn: {
    color: '#D97706',
  },
  gapChipSmallTextWarnActive: {
    color: COLORS.white,
  },
  baseRatingNote: {
    fontSize: 11,
    color: COLORS.textMuted,
    fontStyle: 'italic',
    marginTop: 6,
  },
  categoryBadgeSmall: {
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  catBadgePrimary: {
    backgroundColor: 'rgba(142,36,170,0.1)',
  },
  catBadgeSecondary: {
    backgroundColor: 'rgba(0,128,128,0.1)',
  },
  categoryBadgeSmallText: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  ratingSummaryCard: {
    padding: 14,
    marginTop: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  ratingSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 5,
  },
  ratingSummaryLabel: {
    fontSize: 13,
    color: COLORS.textSecondary,
  },
  ratingSummaryValue: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  optionCard: {
    marginBottom: 8,
    padding: 12,
  },
  optionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  optionName: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textPrimary,
    flex: 1,
  },
  assessmentCard: {
    marginBottom: 12,
    padding: 16,
  },
  assessmentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  worthBadge: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  worthText: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.white,
  },
  assessmentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  assessmentLabelRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  assessmentLabel: {
    fontSize: 14,
    color: COLORS.textPrimary,
  },
  assessmentRating: {
    fontSize: 12,
    color: COLORS.textMuted,
  },
  assessmentInput: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  percentInput: {
    width: 50,
    height: 32,
    backgroundColor: COLORS.background,
    borderRadius: 6,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  percentSign: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginLeft: 4,
  },
  resultCard: {
    marginBottom: 12,
    padding: 16,
  },
  resultCardBest: {
    borderWidth: 2,
    borderColor: COLORS.success,
  },
  resultHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  resultRank: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rankText: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  resultInfo: {
    flex: 1,
    marginLeft: 12,
  },
  resultName: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  resultWorth: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  bestBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  bestText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.warning,
  },
  selectButtons: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
  },
  selectButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  selectButtonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '600',
  },
  selectedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
    gap: 6,
  },
  selectedText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.success,
  },
  caseInfo: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
  },
  caseTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginBottom: 8,
  },
  caseItem: {
    fontSize: 13,
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
  navButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  backButtonText: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  nextButton: {
    flex: 1,
    marginLeft: 16,
  },
  continueButton: {
    marginTop: 8,
  },
  finalButton: {
    marginTop: 20,
    marginBottom: 32,
  },
  // LMH Assessment Styles
  legendCard: {
    marginBottom: 16,
    padding: 12,
  },
  voiceInputRow: {
    marginBottom: 12,
    paddingVertical: 4,
  },
  voiceHintBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(142, 36, 170, 0.06)',
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(142, 36, 170, 0.12)',
  },
  voiceHint: {
    fontSize: 12,
    color: COLORS.textMuted,
    flex: 1,
    fontStyle: 'italic',
  },
  legendTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginBottom: 8,
    textAlign: 'center',
  },
  legendRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  legendText: {
    fontSize: 12,
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  assessmentFactorContainer: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  unitValueRow: {
    marginTop: 6,
    marginBottom: 8,
  },
  unitValueInput: {
    height: 36,
    backgroundColor: COLORS.background,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 13,
    color: COLORS.textPrimary,
  },
  // Unit selector styles (Step 2)
  unitSelectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 6,
  },
  unitSelectorLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS.textMuted,
    minWidth: 30,
  },
  // Expected value & operator styles (Step 2)
  expectedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    gap: 6,
  },
  expectedLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS.textMuted,
    minWidth: 55,
  },
  expectedInput: {
    flex: 1,
    height: 36,
    backgroundColor: COLORS.background,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 14,
    color: COLORS.textPrimary,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  dataTypeBadge: {
    backgroundColor: 'rgba(99,102,241,0.12)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  dataTypeBadgeText: {
    backgroundColor: 'rgba(16,185,129,0.12)',
  },
  dataTypeBadgeLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  operatorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 6,
  },
  operatorLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS.textMuted,
    minWidth: 55,
  },
  operatorChipsContainer: {
    flexDirection: 'row',
    gap: 5,
    paddingRight: 8,
  },
  operatorChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  operatorChipActive: {
    backgroundColor: '#6366F1',
    borderColor: '#6366F1',
  },
  operatorChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  operatorChipTextActive: {
    color: COLORS.white,
  },
  criteriaPreview: {
    backgroundColor: 'rgba(99,102,241,0.1)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    marginRight: 8,
  },
  criteriaPreviewText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6366F1',
  },
  // Sub-factor grouping styles
  factorCardGroup: {
    borderLeftWidth: 3,
    borderLeftColor: COLORS.primary,
  },
  expandBtn: {
    marginRight: 6,
    padding: 2,
  },
  subFactorsContainer: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingTop: 10,
  },
  weightProgressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  weightProgressBar: {
    flex: 1,
    height: 6,
    backgroundColor: COLORS.background,
    borderRadius: 3,
    overflow: 'hidden',
  },
  weightProgressFill: {
    height: '100%',
    backgroundColor: '#F59E0B',
    borderRadius: 3,
  },
  weightProgressText: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.textMuted,
    minWidth: 50,
    textAlign: 'right',
  },
  weightTotalBadge: {
    backgroundColor: 'rgba(245,158,11,0.12)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    marginRight: 6,
  },
  weightTotalComplete: {
    backgroundColor: 'rgba(16,185,129,0.12)',
  },
  weightTotalOver: {
    backgroundColor: 'rgba(239,68,68,0.12)',
  },
  weightTotalText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  subFactorItem: {
    marginBottom: 10,
    paddingLeft: 8,
    borderLeftWidth: 2,
    borderLeftColor: 'rgba(142,36,170,0.2)',
  },
  subFactorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  subFactorDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.primary,
  },
  subFactorName: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    color: COLORS.textPrimary,
  },
  subFactorCriteria: {
    paddingLeft: 12,
    marginTop: 4,
  },
  weightInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 6,
    marginRight: 4,
  },
  weightInput: {
    width: 32,
    height: 28,
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.textPrimary,
    textAlign: 'center',
    padding: 0,
  },
  weightPercent: {
    fontSize: 11,
    color: COLORS.textMuted,
    fontWeight: '600',
  },
  addSubFactorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
    paddingLeft: 8,
  },
  addSubFactorInput: {
    flex: 1,
    height: 32,
    backgroundColor: COLORS.background,
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 12,
    color: COLORS.textPrimary,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderStyle: 'dashed' as any,
  },
  addSubFactorBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addSubToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    paddingVertical: 4,
  },
  addSubToggleText: {
    fontSize: 12,
    color: COLORS.primary,
    fontWeight: '500',
  },
  unitChipsScroll: {
    flex: 1,
  },
  unitChipsContainer: {
    flexDirection: 'row',
    gap: 5,
    paddingRight: 8,
  },
  unitChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.background,
  },
  unitChipActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  unitChipClear: {
    backgroundColor: 'rgba(239,68,68,0.08)',
    borderColor: '#EF4444',
    paddingHorizontal: 6,
  },
  unitChipCustom: {
    borderStyle: 'dashed' as any,
    borderColor: COLORS.primary,
  },
  unitChipText: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  unitChipTextActive: {
    color: COLORS.white,
  },
  unitBadgeSmall: {
    backgroundColor: 'rgba(142,36,170,0.1)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    marginRight: 8,
  },
  unitBadgeSmallText: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.primary,
  },
  customUnitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 8,
  },
  customUnitInput: {
    flex: 1,
    height: 36,
    backgroundColor: COLORS.background,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 13,
    color: COLORS.textPrimary,
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  customUnitApplyBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Step 7 - Separated actual value + unit
  actualValueRow: {
    marginTop: 6,
    marginBottom: 8,
  },
  actualValueInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: 8,
    overflow: 'hidden',
  },
  actualValueInput: {
    flex: 1,
    height: 38,
    paddingHorizontal: 12,
    fontSize: 14,
    color: COLORS.textPrimary,
  },
  unitSuffix: {
    backgroundColor: 'rgba(142,36,170,0.1)',
    paddingHorizontal: 10,
    height: 38,
    justifyContent: 'center',
    alignItems: 'center',
    borderLeftWidth: 1,
    borderLeftColor: COLORS.border,
  },
  unitSuffixText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.primary,
  },
  factorUnitBadge: {
    backgroundColor: 'rgba(142,36,170,0.1)',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 8,
    marginLeft: 6,
  },
  factorUnitBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: COLORS.primary,
  },
  expectedCriteriaBadge: {
    backgroundColor: 'rgba(99,102,241,0.1)',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 8,
    marginLeft: 4,
  },
  expectedCriteriaText: {
    fontSize: 9,
    fontWeight: '600',
    color: '#6366F1',
  },
  currentValueBadgeAuto: {
    backgroundColor: 'rgba(99,102,241,0.12)',
    borderWidth: 1,
    borderColor: '#6366F1',
  },
  currentValueTextAuto: {
    color: '#6366F1',
    fontWeight: '700',
  },
  percentBadgeInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  lmhContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  lmhButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  lmhText: {
    fontSize: 16,
    fontWeight: '700',
  },
  customButton: {
    borderColor: COLORS.primary,
  },
  customButtonActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  customInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: 8,
    paddingHorizontal: 8,
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  customPercentInput: {
    width: 40,
    height: 36,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  customPercentSign: {
    fontSize: 14,
    color: COLORS.primary,
    fontWeight: '600',
  },
  currentValueBadge: {
    marginLeft: 'auto',
    backgroundColor: COLORS.primary,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  currentValueBadgeEmpty: {
    backgroundColor: COLORS.textMuted,
  },
  currentValueText: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.white,
  },
  currentValueTextEmpty: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.white,
  },
  worthBadgeEmpty: {
    backgroundColor: COLORS.textMuted,
  },
  worthTextEmpty: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.white,
  },
  assessmentProgress: {
    marginBottom: 8,
  },
  progressText: {
    fontSize: 12,
    color: COLORS.textSecondary,
    fontStyle: 'italic',
  },
});
