/* Pros & Cons wizard — StyleSheets (extracted). */
import { StyleSheet, Platform } from 'react-native';
import { COLORS } from './constants';

export const pcMeta = StyleSheet.create({
  wrap: { backgroundColor: '#FAFBFF', borderWidth: 1, borderColor: '#E5E9F2', borderRadius: 10, padding: 10, marginTop: 6, gap: 8 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  label: { fontSize: 11.5, fontWeight: '700', color: COLORS.textDim, width: 64 },
  toggle: { flexDirection: 'row', borderWidth: 1, borderColor: COLORS.border, borderRadius: 8, overflow: 'hidden' },
  toggleBtn: { paddingHorizontal: 12, paddingVertical: 7, backgroundColor: '#fff' },
  toggleQuant: { backgroundColor: '#1F6FEB' },
  toggleQual: { backgroundColor: '#7C3AED' },
  toggleText: { fontSize: 12, fontWeight: '700', color: COLORS.textDim },
  toggleTextOn: { color: '#fff' },
  input: { flex: 1, minWidth: 90, height: 34, borderWidth: 1, borderColor: COLORS.border, borderRadius: 8, paddingHorizontal: 10, fontSize: 13, color: COLORS.text, backgroundColor: '#fff' },
  opWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, flex: 1 },
  opChip: { minWidth: 34, paddingHorizontal: 8, paddingVertical: 6, borderRadius: 7, borderWidth: 1, borderColor: COLORS.border, backgroundColor: '#fff', alignItems: 'center' },
  opChipActive: { backgroundColor: '#0F766E', borderColor: '#0F766E' },
  opText: { fontSize: 12, fontWeight: '700', color: COLORS.textDim },
  dsBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 8, paddingHorizontal: 10, borderRadius: 8, borderWidth: 1, borderColor: '#DDD6FE', backgroundColor: '#F5F3FF' },
  dsBtnText: { flex: 1, fontSize: 12.5, fontWeight: '700', color: '#7C3AED' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalCard: { backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 18, paddingBottom: 28 },
  modalHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  modalTitle: { fontSize: 17, fontWeight: '800', color: COLORS.text },
  dsOpt: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 12, borderRadius: 10, borderWidth: 1, borderColor: COLORS.border, marginBottom: 8, backgroundColor: '#fff' },
  dsOptOn: { borderColor: '#7C3AED', backgroundColor: '#F5F3FF' },
  dsOptLabel: { fontSize: 14, fontWeight: '700', color: COLORS.text },
  dsOptHint: { fontSize: 11.5, color: COLORS.textDim, marginTop: 1 },
  cfgBox: { marginTop: 6, marginBottom: 4, gap: 4 },
  cfgLabel: { fontSize: 12, fontWeight: '700', color: COLORS.textDim, marginTop: 6 },
  cfgInput: { borderWidth: 1, borderColor: COLORS.border, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 9, fontSize: 13, color: COLORS.text, backgroundColor: '#fff' },
  saveBtn: { backgroundColor: '#7C3AED', borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 14 },
  saveBtnText: { color: '#fff', fontWeight: '800', fontSize: 15 },
  addSubBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 7, borderRadius: 8, borderWidth: 1, borderColor: '#BBF7D0', backgroundColor: '#F0FDF4', marginTop: 8 },
  addSubText: { fontSize: 12, fontWeight: '700', color: '#15803D' },
});

export const pcAssess = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  lmh: { width: 26, height: 28, borderRadius: 6, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  lmhText: { fontSize: 12, fontWeight: '800', color: COLORS.textDim },
  aiBtn: { flexDirection: 'row', alignItems: 'center', gap: 3, height: 28, paddingHorizontal: 8, borderRadius: 6, borderWidth: 1, borderColor: '#DDD6FE', backgroundColor: '#F5F3FF' },
  aiText: { fontSize: 11, fontWeight: '800', color: '#7C3AED' },
  xlsBar: { flexDirection: 'row', gap: 8, marginTop: 8, marginBottom: 4, flexWrap: 'wrap' },
  xlsBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: '#BBD6FF', backgroundColor: '#EFF6FF' },
  xlsBtnText: { fontSize: 12.5, fontWeight: '700', color: '#1F6FEB' },
});

export const pcWeightStyles = StyleSheet.create({
  totalBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10, backgroundColor: '#E2E8F0' },
  totalOk: { backgroundColor: '#10B981' },
  totalOver: { backgroundColor: '#EF4444' },
  totalText: { fontSize: 11, fontWeight: '800', color: '#475569' },
  splitRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 6, paddingHorizontal: 4 },
  weightHint: { flex: 1, fontSize: 10.5, color: COLORS.textDim, lineHeight: 15 },
  splitBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10, backgroundColor: '#F5F3FF', borderWidth: 1, borderColor: '#DDD6FE' },
  splitBtnText: { fontSize: 11, fontWeight: '700', color: '#7C3AED' },
  weightWrap: { flexDirection: 'row', alignItems: 'center', gap: 2, marginLeft: 6 },
  weightInput: { minWidth: 38, height: 30, borderWidth: 1, borderColor: COLORS.border, borderRadius: 8, paddingHorizontal: 6, fontSize: 13, fontWeight: '700', color: COLORS.text, textAlign: 'center', backgroundColor: '#fff' },
  weightPct: { fontSize: 12, color: COLORS.textDim, fontWeight: '700' },
  subBlock: { borderLeftWidth: 2, borderLeftColor: '#E5E9F2', paddingLeft: 8, marginBottom: 10, marginTop: 2 },
});

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: { paddingHorizontal: 12, paddingVertical: 12, flexDirection: 'row', alignItems: 'center', gap: 8 },
  headerBtn: { padding: 6 },
  headerTitle: { color: '#fff', fontSize: 17, fontWeight: '700' },
  headerSub: { color: 'rgba(255,255,255,0.85)', fontSize: 12, marginTop: 2 },
  stepStrip: { backgroundColor: '#fff', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  stepChip: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 16, backgroundColor: COLORS.bg, marginHorizontal: 3, borderWidth: 1, borderColor: COLORS.border },
  stepChipActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  stepChipNum: { fontWeight: '700', fontSize: 12, color: COLORS.text, width: 14, textAlign: 'center' },
  stepChipLabel: { fontSize: 12, color: COLORS.textDim },
  body: { padding: 12, paddingBottom: 60 },
  stepTitle: { fontSize: 18, fontWeight: '800', color: COLORS.text, marginBottom: 4 },
  stepHint: { fontSize: 12, color: COLORS.textDim, marginBottom: 12, lineHeight: 18 },
  sectionTitle: { fontSize: 14, fontWeight: '700', color: COLORS.text, marginTop: 14, marginBottom: 6 },
  card: { backgroundColor: COLORS.card, borderRadius: 12, padding: 12, borderWidth: 1, borderColor: COLORS.border, marginBottom: 12 },
  inputLabel: { fontSize: 12, color: COLORS.textDim, marginTop: 6, marginBottom: 4 },
  input: { backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.border, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8, fontSize: 14, color: COLORS.text, marginBottom: 8 },
  inputSm: { backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.border, borderRadius: 6, paddingHorizontal: 6, paddingVertical: 4, fontSize: 12, color: COLORS.text, textAlign: 'center' },
  primaryBtn: { backgroundColor: COLORS.primary, paddingVertical: 10, paddingHorizontal: 14, borderRadius: 8, alignItems: 'center', flexDirection: 'row', gap: 6, alignSelf: 'flex-start' },
  primaryBtnText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  factorRow: { backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', padding: 10, borderRadius: 8, marginBottom: 6, gap: 8, borderWidth: 1, borderColor: COLORS.border, flexWrap: 'wrap' },
  sourceTag: { width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  sourceTagText: { color: '#fff', fontSize: 11, fontWeight: '800' },
  factorName: { fontSize: 14, fontWeight: '600', color: COLORS.text },
  factorMeta: { fontSize: 11, color: COLORS.textDim, marginTop: 2 },
  optionCard: { backgroundColor: '#fff', borderRadius: 12, padding: 10, marginBottom: 10, borderWidth: 1, borderColor: COLORS.border },  optionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
  optionName: { fontSize: 15, fontWeight: '700', color: COLORS.text },
  pcSection: { fontSize: 12, fontWeight: '600', color: COLORS.textDim, marginTop: 6 },
  pcRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 8, marginVertical: 2, backgroundColor: COLORS.bg, borderLeftWidth: 3, borderRadius: 4 },
  pcText: { flex: 1, fontSize: 13, color: COLORS.text },
  addPcBar: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 8 },
  pcKindBtn: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6, backgroundColor: COLORS.bg, borderWidth: 1, borderColor: COLORS.border },
  pcKindBtnText: { fontSize: 12, fontWeight: '700', color: COLORS.text },
  miniBtn: { backgroundColor: COLORS.primary, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6, alignItems: 'center', justifyContent: 'center' },
  bigCta: { borderRadius: 12, overflow: 'hidden', marginVertical: 6 },
  bigCtaGrad: { paddingVertical: 14, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 8 },
  bigCtaText: { color: '#fff', fontWeight: '800', fontSize: 15 },
  linkBtn: { paddingHorizontal: 8, paddingVertical: 4, backgroundColor: COLORS.bg, borderRadius: 6, borderWidth: 1, borderColor: COLORS.border },
  linkBtnText: { fontSize: 11, color: COLORS.text, fontWeight: '600' },
  parentChip: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, backgroundColor: COLORS.bg, borderWidth: 1, borderColor: COLORS.border, maxWidth: 160 },
  parentChipActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  parentChipText: { fontSize: 11, color: COLORS.text },
  treeNode: { backgroundColor: '#fff', borderRadius: 8, marginBottom: 6, padding: 8, borderWidth: 1, borderColor: COLORS.border },
  treeHead: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  treeChild: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 24, paddingTop: 4 },
  subFactorReadRow: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 4 },
  subFactorEditCard: {
    backgroundColor: COLORS.bg,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 10,
    gap: 4,
  },

  // ─── Std-rating read-only chip (Step 7) ────────────────────────
  readOnlyChip: {
    paddingHorizontal: 12, paddingVertical: 4,
    borderRadius: 8, borderWidth: 2,
    backgroundColor: '#FFFFFF',
    minWidth: 48, alignItems: 'center',
  },
  readOnlyChipText: { fontSize: 16, fontWeight: '800' },

  // ─── Realistic Gap selector (Step 7 top card) ──────────────────
  gapSelectorCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 12,
    marginBottom: 16,
  },
  gapSelectorTitle: { fontSize: 13, fontWeight: '700', color: COLORS.text },
  gapSelectorCurrent: {
    fontSize: 11, fontWeight: '700', color: COLORS.primary,
    backgroundColor: 'rgba(99,102,241,0.1)',
    paddingHorizontal: 8, paddingVertical: 2, borderRadius: 8,
  },
  gapSelectorRow: { flexDirection: 'row', gap: 6 },
  gapSelectorBtn: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    paddingVertical: 8, paddingHorizontal: 4,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  gapSelectorBtnActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  gapSelectorPct: { fontSize: 12, fontWeight: '800', color: COLORS.primary },
  gapSelectorGap: { fontSize: 14, fontWeight: '900', color: COLORS.text, marginTop: 2 },
  gapSelectorLabel: { fontSize: 10, color: COLORS.textDim, marginTop: 2 },

  // ─── Step 7 — Per-pair Gap Connector (between adjacent factor cards) ───
  gapConnector: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginVertical: 4,
    marginHorizontal: 6,
  },
  gapConnectorRail: {
    width: 2,
    backgroundColor: COLORS.border,
    marginHorizontal: 8,
    borderRadius: 1,
  },
  gapConnectorInner: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: Platform.OS === 'web' ? ('dashed' as any) : 'solid',
    borderColor: COLORS.border,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  gapConnectorLabel: {
    fontSize: 11,
    color: COLORS.textDim,
    marginBottom: 6,
    textAlign: 'center',
  },
  gapConnectorRow: { flexDirection: 'row', gap: 6 },
  gapConnectorBtn: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    paddingVertical: 6,
    paddingHorizontal: 4,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  gapConnectorBtnActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  gapConnectorPct: { fontSize: 12, fontWeight: '800', color: COLORS.primary },
  gapConnectorAdd: { fontSize: 11, fontWeight: '700', color: COLORS.text, marginTop: 1 },

  // ─── Step 8 — Case-2 (MPPS) section header + Max Time input ───
  case2Header: {
    backgroundColor: '#EEF2FF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#C7D2FE',
    padding: 14,
    marginTop: 14,
    marginBottom: 10,
  },
  case2Title: { fontSize: 15, fontWeight: '900', color: COLORS.text },
  case2Sub: { fontSize: 12, color: COLORS.textDim, marginTop: 4, lineHeight: 17 },
  mppsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  mppsLabel: { fontSize: 12, fontWeight: '700', color: COLORS.text },
  mppsUnitRow: { flexDirection: 'row', gap: 4, flexWrap: 'wrap' },
  mppsUnitBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: '#FFFFFF',
  },
  mppsUnitBtnOn: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  mppsUnitText: { fontSize: 11, fontWeight: '700', color: COLORS.text },

  // ─── Step 8 — A / B section split percentages (subtotals under each option's Score)
  // Color cue: A (mandatory) in amber-orange, B (optional) in steel-blue — matches
  // the colour language used in Step 7 section headers (mandatory/optional).
  sectionPctA: { fontSize: 11, fontWeight: '800', color: '#B45309' /* amber-700 */ },
  sectionPctB: { fontSize: 11, fontWeight: '800', color: '#1D4ED8' /* blue-700  */ },
  sectionPctSep: { fontSize: 11, color: COLORS.textDim },

  // ─── Step 8 — Final Decision capture card ───
  finalCard: {
    marginTop: 16,
    padding: 16,
    borderRadius: 14,
    backgroundColor: '#FFFBEB',
    borderWidth: 1.5,
    borderColor: '#FCD34D',
  },
  finalTitle: { fontSize: 16, fontWeight: '900', color: '#92400E' },
  finalSub: { fontSize: 12, color: '#78350F', marginTop: 2, lineHeight: 17 },
  finalLabel: { fontSize: 12, fontWeight: '800', color: COLORS.text, marginTop: 8 },
  finalOptChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: '#FCD34D',
    backgroundColor: '#FFFFFF',
    maxWidth: '100%',
  },
  finalOptChipOn: {
    backgroundColor: '#92400E',
    borderColor: '#92400E',
  },
  finalOptChipText: { fontSize: 13, fontWeight: '700', color: COLORS.text },
  finalReason: {
    minHeight: 72,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: '#FFFFFF',
    fontSize: 13,
    color: COLORS.text,
    textAlignVertical: 'top',
    marginTop: 4,
  },
  finalStamp: {
    marginTop: 10,
    fontSize: 11,
    fontStyle: 'italic',
    color: '#78350F',
  },

  // ─── Step 7 — Mandatory (A) / Optional (B) section boxes ─────
  sectionBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 12,
    marginBottom: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 10,
    marginHorizontal: -4,
    marginTop: -4,
  },
  sectionHeaderBadge: {
    width: 24, height: 24, borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.25)',
    justifyContent: 'center', alignItems: 'center',
  },
  sectionHeaderBadgeText: { color: '#FFFFFF', fontWeight: '900', fontSize: 13 },
  sectionHeaderTitle: { color: '#FFFFFF', fontWeight: '700', fontSize: 15, flex: 1 },
  sectionHeaderCount: {
    color: '#FFFFFF',
    backgroundColor: 'rgba(0,0,0,0.15)',
    paddingHorizontal: 8, paddingVertical: 2,
    borderRadius: 10,
    fontSize: 12, fontWeight: '700',
    minWidth: 24, textAlign: 'center',
  },
  sectionEmpty: {
    color: COLORS.textDim,
    fontStyle: 'italic',
    paddingVertical: 12,
    paddingHorizontal: 8,
    textAlign: 'center',
    fontSize: 13,
  },
  notationBtn: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6, backgroundColor: COLORS.bg, borderWidth: 1, borderColor: COLORS.border, marginLeft: 4 },
  notationMandActive: { backgroundColor: COLORS.warn, borderColor: COLORS.warn },
  notationOptActive: { backgroundColor: COLORS.textDim, borderColor: COLORS.textDim },
  notationBtnText: { fontSize: 12, fontWeight: '800', color: COLORS.text },
  factorCard: { backgroundColor: '#fff', borderRadius: 10, padding: 10, marginBottom: 10, borderWidth: 1, borderColor: COLORS.border },
  factorCardHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  rankBadge: { backgroundColor: COLORS.primary, color: '#fff', fontSize: 12, fontWeight: '800', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, overflow: 'hidden' },
  assessRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 6, flexWrap: 'wrap' },
  assessOpt: { fontSize: 12, color: COLORS.text, fontWeight: '600', width: 80 },
  cellLabel: { fontSize: 11, color: COLORS.textDim },
  cellValue: { fontSize: 12, color: COLORS.text, fontWeight: '700', minWidth: 36 },
  overallRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  overallPct: { fontSize: 18, fontWeight: '800', color: COLORS.primary },
  tinyChip: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, backgroundColor: COLORS.bg, borderWidth: 1, borderColor: COLORS.border },
  tinyChipOn: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  tinyChipText: { fontSize: 11, color: COLORS.text, fontWeight: '600' },
  navBar: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 16 },
  navBtn: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 10, borderRadius: 8, backgroundColor: COLORS.card, borderWidth: 1, borderColor: COLORS.border, gap: 4 },
  navBtnPrimary: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 10, borderRadius: 8, backgroundColor: COLORS.primary, gap: 4 },
  navBtnText: { fontSize: 13, fontWeight: '700', color: COLORS.text },
  modalBg: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', justifyContent: 'center', alignItems: 'center', padding: 18 },
  modalCard: { backgroundColor: '#fff', borderRadius: 16, padding: 18, maxHeight: '90%', width: '100%', maxWidth: 640, shadowColor: '#000', shadowOpacity: 0.18, shadowRadius: 16, shadowOffset: { width: 0, height: 4 }, elevation: 8 },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  modalTitle: { fontSize: 17, fontWeight: '800', color: COLORS.text },
  gRow: { flexDirection: 'row', gap: 10, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  gRank: { fontSize: 13, fontWeight: '800', color: COLORS.primary, width: 24 },
  gRule: { flex: 1, fontSize: 13, color: COLORS.text, lineHeight: 18 },

  // Basics card (Step 1 prefix — Decision / Description / Life Area)
  basicsCard: {
    backgroundColor: COLORS.card, borderRadius: 12,
    borderWidth: 1, borderColor: COLORS.border,
    marginBottom: 12, overflow: 'hidden',
  },
  basicsHeader: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    paddingHorizontal: 12, paddingVertical: 10,
    backgroundColor: '#EEF2FF',
  },
  basicsTitle: { fontSize: 14, fontWeight: '700', color: COLORS.text },
  basicsSummary: { fontSize: 11, color: COLORS.textDim, marginTop: 2 },
  basicsBody: { padding: 12, gap: 2 },
  lifeChip: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    paddingHorizontal: 10, paddingVertical: 6, borderRadius: 14,
    backgroundColor: COLORS.bg, borderWidth: 1, borderColor: COLORS.border,
  },
  lifeChipActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  lifeChipText: { fontSize: 11, fontWeight: '600', color: COLORS.textDim },

  // Inline-edit affordances for factors + options
  factorRowEditing: {
    backgroundColor: '#F0F4FF',
    borderColor: COLORS.primary,
  },
  editGhostBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editGhostBtnText: { fontSize: 12, fontWeight: '600', color: COLORS.textDim },
  editSaveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
  },
  editSaveBtnText: { fontSize: 12, fontWeight: '700', color: '#fff' },

  // Step 2 — "Add Option" affordance (now perfectly centre-aligned with input)
  addOptBtn: {
    width: 44, height: 44, borderRadius: 12,
    alignItems: 'center', justifyContent: 'center',
    backgroundColor: COLORS.primary,
  },
  optionSummary: { fontSize: 11, color: COLORS.textDim, marginTop: 2 },
  pcSectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 10,
    marginBottom: 4,
  },

  // Step 4 — de-dup / group visual states
  factorRowSub: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderStyle: 'dashed' as any,
  },
  factorRowDuplicate: {
    backgroundColor: '#FFFBEB',
    borderColor: '#FCD34D',
    opacity: 0.85,
  },
  linkBtnMuted: {
    backgroundColor: '#E5E7EB',
  },

  // Step 4 — Mark-Duplicate / Restore labeled pill button
  // Mirrors the Group/Move pill but with an action-specific tint so users
  // immediately see this is a different (destructive-but-reversible) action.
  dupBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 12,
    marginLeft: 8,
    borderWidth: 1,
  },
  dupBtnMark: {
    backgroundColor: '#FEF3C7',  // warm amber
    borderColor: '#FCD34D',
  },
  dupBtnRestore: {
    backgroundColor: '#DCFCE7',  // light green
    borderColor: '#86EFAC',
  },
  dupBtnText: {
    fontSize: 11,
    fontWeight: '700',
  },
  parentPickerLabel: {
    fontSize: 12,
    color: COLORS.textDim,
    marginBottom: 6,
    lineHeight: 16,
  },
  dedupLegend: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 12,
    overflow: 'hidden',
  },
  dedupLegendItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
  },
  dedupLegendNum: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.primary,
  },
  dedupLegendLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.textDim,
    marginTop: 2,
    textTransform: 'uppercase' as any,
    letterSpacing: 0.5,
  },
});

